name: Dart CI

on:
  push:
    branches:
      - v3*
  pull_request:
    branches:
      - v3*

jobs:
  integration_test_linux:
    name: Integration Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - name: Install Linux requirements
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v4
      - name: Build Isar Core
        run: |
          bash tool/build_linux.sh x64
          mv libisar_linux_x64.so packages/isar_flutter_libs/linux/libisar.so
      - name: Prepare Tests
        run: sh tool/prepare_tests.sh
      - name: Run Flutter Driver tests
        run: |
          flutter config --enable-linux-desktop 
          flutter test -d linux integration_test/integration_test.dart --dart-define STRESS=true
        working-directory: packages/isar_test

  integration_test_linux_arm:
    name: Integration Test ARM Linux
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Prebuilt ARM linux builds are not provided, so build flutter from source
          channel: master
          flutter-version: "3.3.10"
      - run: flutter --version
      - name: Install Linux requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v4
      - name: Display Rust version
        run: rustc --version && cargo --version
      - name: Build Isar Core
        run: |
          bash tool/build_linux.sh aarch64
          mv libisar_linux_arm64.so packages/isar_flutter_libs/linux/libisar.aarch64.so
      - name: Prepare Tests
        run: sh tool/prepare_tests.sh
      - name: Run Flutter Driver tests
        run: |
          flutter config --enable-linux-desktop
          flutter test -d linux integration_test/integration_test.dart --dart-define STRESS=true
        working-directory: packages/isar_test

  integration_test_windows:
    name: Integration Test Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - name: Prepare Build
        uses: ./.github/actions/prepare-build
      - name: Display Rust version
        run: rustc --version && cargo --version
      - name: Build Isar Core
        run: |
          bash tool/build_windows.sh x64
          mv isar_windows_x64.dll packages/isar_flutter_libs/windows/libisar.dll
      - name: Prepare Tests
        run: sh tool/prepare_tests.sh
      - name: Run Flutter Driver tests
        run: |
          flutter config --enable-windows-desktop 
          flutter test -d windows integration_test/integration_test.dart --dart-define STRESS=true
        working-directory: packages/isar_test

  integration_test_windows_arm:
    name: Integration Test Windows ARM
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Prebuilt ARM windows builds are not provided, so build flutter from source
          channel: master
          flutter-version: "3.3.10"
      - run: flutter --version
      - name: Prepare Build
        uses: ./.github/actions/prepare-build
      - name: Display Rust version
        run: rustc --version && cargo --version
      - name: Build Isar Core
        run: |
          bash tool/build_windows.sh aarch64
          mv isar_windows_arm64.dll packages/isar_flutter_libs/windows/libisar.dll
      - name: Prepare Tests
        run: sh tool/prepare_tests.sh
      - name: Run Flutter Driver tests
        run: |
          flutter config --enable-windows-desktop 
          flutter test -d windows integration_test/integration_test.dart --dart-define STRESS=true
        working-directory: packages/isar_test

  integration_test_android:
    name: Integration Test Android
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - name: Free Disk Space (Ubuntu)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          df -h
      - name: Prepare Build
        uses: ./.github/actions/prepare-build
      - name: Build Isar Core
        run: |
          bash tool/build_android.sh x64
          bash tool/build_android.sh arm64
          mkdir -p packages/isar_flutter_libs/android/src/main/jniLibs/x86_64
          cp libisar_android_x64.so packages/isar_flutter_libs/android/src/main/jniLibs/x86_64/libisar.so
      - uses: actions/upload-artifact@v6
        with:
          name: libisar_android_x64.so
          path: libisar_android_x64.so
      - uses: actions/upload-artifact@v6
        with:
          name: libisar_android_arm64.so
          path: libisar_android_arm64.so
      - name: Prepare Tests
        run: sh tool/prepare_tests.sh
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run Flutter Integration tests
        timeout-minutes: 20
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: reactivecircus/android-emulator-runner@v2
          with: |
            api-level: 29
            arch: x86_64
            profile: pixel
            working-directory: packages/isar_test
            disk-size: 5120M
            script: |
              adb logcat -c
              adb logcat &
              flutter test integration_test/integration_test.dart --dart-define STRESS=true